# Generated by Django 4.2.15 on 2024-10-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='session_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
