# Generated by Django 4.2.15 on 2024-10-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_admin', '0002_session_agendaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='agendaitem',
            name='session',
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='building',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='room_num',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='session_num',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
