# Generated by Django 4.2.15 on 2024-10-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_admin', '0002_alter_agendaitem_session_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.BooleanField()),
            ],
        ),
    ]
