# Generated by Django 4.2.15 on 2024-10-30 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_admin', '0003_registrationpermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationPermission',
            new_name='RegistrationFlag',
        ),
    ]
