# Generated by Django 4.2.15 on 2024-11-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_admin', '0004_rename_registrationpermission_registrationflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
