# Generated by Django 4.2.15 on 2025-06-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_admin', '0005_agendaitem_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='address',
            field=models.CharField(blank=True, help_text='Optional address for events', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='building',
            field=models.CharField(help_text='The building where the event will take place', max_length=100),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='end_time',
            field=models.DateTimeField(help_text='The scheduled end time of the event'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='room_num',
            field=models.CharField(help_text='The room number where the event will take place', max_length=100),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='session_num',
            field=models.IntegerField(blank=True, help_text='Optional session number for events with multiple sessions', null=True),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='start_time',
            field=models.DateTimeField(help_text='The scheduled start time of the event'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='title',
            field=models.CharField(help_text='The title or name of the agenda item', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expiration',
            field=models.DateTimeField(help_text='The date and time when this notification should expire'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(help_text='The notification message to be displayed (max 180 characters)', max_length=180),
        ),
        migrations.AlterField(
            model_name='registrationflag',
            name='label',
            field=models.CharField(help_text='Unique identifier for the flag', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationflag',
            name='value',
            field=models.BooleanField(help_text='The current state of the flag (True/False)'),
        ),
    ]
