# Generated by Django 4.2.15 on 2025-10-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_admin', '0006_alter_agendaitem_address_alter_agendaitem_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='building',
            field=models.CharField(blank=True, help_text='Optional building where the event will take place', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='room_num',
            field=models.CharField(blank=True, help_text='Optional room number where the event will take place', max_length=100, null=True),
        ),
    ]
