# Generated by Django 4.2.15 on 2024-10-26 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronouns', models.CharField(default='', max_length=30)),
                ('year', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(blank=True, max_length=100)),
                ('fa_contact', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(default='', max_length=50)),
                ('building', models.CharField(default='', max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('session', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('facilitators', models.JSONField(default=list)),
                ('session', models.IntegerField(default=0)),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.location')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.delegate')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='FacilitatorWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.facilitator')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.workshop')),
            ],
        ),
        migrations.AddField(
            model_name='delegate',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.school'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
