# Generated by Django 5.0 on 2024-07-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(default='', max_length=50)),
                ('building', models.CharField(default='', max_length=50)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('facilitators', models.JSONField(default=list)),
                ('session', models.IntegerField(default=0)),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.location')),
            ],
        ),
    ]
