# Generated by Django 5.0 on 2024-06-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_facilitator',
            field=models.CharField(default='', max_length=300),
        ),
    ]
