# Generated by Django 5.0 on 2024-06-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
    ]
