# Generated by Django 5.0 on 2024-07-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.location'),
        ),
    ]
