# Generated by Django 5.0 on 2024-06-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='room_num',
            field=models.CharField(max_length=50),
        ),
    ]
