# Generated by Django 5.1 on 2024-08-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_workshop_location'),
        ('registration', '0002_workshop_workshop_facilitator'),
    ]

    operations = [
    ]
