# Generated by Django 4.2.15 on 2024-10-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilitator',
            name='department_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilitator',
            name='facilitators',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
