# Generated by Django 5.0 on 2024-06-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_location_building_alter_location_room_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='room_num',
            field=models.CharField(default='', max_length=50),
        ),
    ]
