# Generated by Django 4.2.15 on 2024-10-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_facilitator_bio_facilitator_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='year',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.location'),
        ),
    ]
