# Generated by Django 5.1 on 2024-08-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_merge_20240815_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='workshop_facilitator',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.location'),
        ),
    ]
