# Generated by Django 4.2.15 on 2024-10-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_delegate_year_alter_workshop_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSetUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=100)),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
