# Generated by Django 5.0 on 2024-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_location_building_alter_location_room_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
