# Generated by Django 5.1 on 2024-08-15 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_school_delegate_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.school'),
        ),
    ]
