# Generated by Django 4.2.15 on 2024-10-29 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_accountsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitatorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitator_name', models.CharField(max_length=200)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.workshop')),
            ],
        ),
    ]
