# Generated by Django 5.1 on 2024-08-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_delegate_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='session',
            field=models.IntegerField(default=0),
        ),
    ]
