# Generated by Django 4.2.15 on 2024-10-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_facilitatorassistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='delegate',
            name='other_school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
