# Generated by Django 4.2.15 on 2024-10-30 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_newschool_delegate_other_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
