# Generated by Django 4.2.15 on 2024-10-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_facilitator_facilitatorworkshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='facilitators',
            field=models.JSONField(default=list, null=True),
        ),
    ]
