# Generated by Django 4.2.15 on 2024-10-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_workshop_facilitators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='facilitators',
            field=models.JSONField(default=list),
        ),
    ]
