# Generated by Django 4.2.15 on 2024-10-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_delegate_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='facilitators',
        ),
    ]
