# Generated by Django 4.2.15 on 2024-10-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_workshop_facilitators'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.location'),
        ),
    ]
