# Generated by Django 4.2.15 on 2024-10-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_remove_workshop_facilitators'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='attending_networking_session',
            field=models.BooleanField(default=False),
        ),
    ]
