# Generated by Django 4.2.15 on 2024-10-17 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_workshop_id_alter_workshop_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.location'),
        ),
    ]
