# Generated by Django 4.2.15 on 2024-11-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_facilitator_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='moveable_seats',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='moveable_seats',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='preferred_cap',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
