# Generated by Django 4.2.15 on 2024-11-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_location_moveable_seats_workshop_moveable_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='preferred_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
