# Generated by Django 4.2.15 on 2025-06-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_alter_workshop_preferred_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='moveable_seats',
            field=models.BooleanField(default=False),
        ),
    ]
