# Generated by Django 4.2.15 on 2025-06-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_alter_location_moveable_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='moveable_seats',
            field=models.BooleanField(default=False),
        ),
    ]
