# Generated by Django 4.2.15 on 2025-10-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_workshop_moveable_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
