# Generated by Django 4.2.15 on 2025-10-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_alter_workshop_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsetup',
            name='token',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='other_school',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='department_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='fa_contact',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='fa_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='facilitatorassistant',
            name='contact',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='newschool',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
